// Arayüz metinleri (11 dil). Her satır: [anahtar, tr, en, de, fr, es, it, pt, ru, zh, ja, ko].
// Bu dosya hem main (bildirim, tepsi, diyalog) hem renderer tarafından kullanılır.

export const I18N_LANGS = ["tr", "en", "de", "fr", "es", "it", "pt", "ru", "zh", "ja", "ko"] as const;
export type UiLang = (typeof I18N_LANGS)[number];

/** Her dilin kendi yazımıyla adı (dil menüsünde sabit gösterilir). */
export const LANG_AUTONYMS: Record<UiLang, string> = {
  tr: "Türkçe", en: "English", de: "Deutsch", fr: "Français", es: "Español",
  it: "Italiano", pt: "Português", ru: "Русский", zh: "中文", ja: "日本語", ko: "한국어",
};

export const LOCALE_TAGS: Record<UiLang, string> = {
  tr: "tr-TR", en: "en-US", de: "de-DE", fr: "fr-FR", es: "es-ES",
  it: "it-IT", pt: "pt-PT", ru: "ru-RU", zh: "zh-CN", ja: "ja-JP", ko: "ko-KR",
};

export const I18N_ROWS: string[][] = [
  ["pageTitle","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu","YazBunu"],
  ["diarizeLabel","Konuşmacı ayrımı","Speaker diarization","Sprechererkennung","Séparation des locuteurs","Diarización de hablantes","Diarizzazione dei parlanti","Diarização de locutores","Разделение говорящих","说话人分离","話者分離","화자 분리"],
  ["langSwitcherAria","Uygulama dilini değiştir","Change app language","App-Sprache ändern","Changer la langue de l'application","Cambiar idioma de la aplicación","Cambia lingua dell'app","Alterar idioma do aplicativo","Изменить язык приложения","更改应用语言","アプリの言語を変更","앱 언어 변경"],
  ["historyAria","Geçmiş","History","Verlauf","Historique","Historial","Cronologia","Histórico","История","历史记录","履歴","기록"],
  ["themeAria","Temayı değiştir","Toggle theme","Design wechseln","Changer de thème","Cambiar tema","Cambia tema","Alternar tema","Сменить тему","切换主题","テーマを切り替え","테마 전환"],
  ["settingsTitle","Ayarlar","Settings","Einstellungen","Paramètres","Ajustes","Impostazioni","Configurações","Настройки","设置","設定","설정"],
  ["closeAria","Kapat","Close","Schließen","Fermer","Cerrar","Chiudi","Fechar","Закрыть","关闭","閉じる","닫기"],
  ["setupBannerText","<strong>Hızlı başla:</strong> Transkript, çeviri ve özet için ücretsiz bir <b>Groq</b> API anahtarı gir. Kart gerekmez, 1 dakikada alınır.","<strong>Quick start:</strong> Enter a free <b>Groq</b> API key for transcription, translation, and summaries. No card needed, takes 1 minute.","<strong>Schnellstart:</strong> Gib einen kostenlosen <b>Groq</b>-API-Schlüssel für Transkription, Übersetzung und Zusammenfassungen ein. Keine Karte nötig, dauert 1 Minute.","<strong>Démarrage rapide :</strong> Entrez une clé API <b>Groq</b> gratuite pour la transcription, la traduction et les résumés. Aucune carte requise, cela prend 1 minute.","<strong>Inicio rápido:</strong> Introduce una clave API de <b>Groq</b> gratuita para transcripción, traducción y resúmenes. No necesitas tarjeta, toma 1 minuto.","<strong>Avvio rapido:</strong> Inserisci una chiave API <b>Groq</b> gratuita per trascrizione, traduzione e riepiloghi. Nessuna carta richiesta, 1 minuto.","<strong>Início rápido:</strong> Insira uma chave de API <b>Groq</b> gratuita para transcrição, tradução e resumos. Não precisa de cartão, leva 1 minuto.","<strong>Быстрый старт:</strong> Введите бесплатный API-ключ <b>Groq</b> для транскрипции, перевода и резюме. Карта не нужна, займёт 1 минуту.","<strong>快速开始：</strong>输入免费的 <b>Groq</b> API 密钥即可使用转录、翻译和摘要功能。无需信用卡，1 分钟即可完成。","<strong>クイックスタート：</strong>文字起こし・翻訳・要約には無料の <b>Groq</b> APIキーを入力してください。カード不要、1分で完了します。","<strong>빠른 시작:</strong> 전사, 번역, 요약을 위해 무료 <b>Groq</b> API 키를 입력하세요. 카드 없이 1분이면 충분합니다."],
  ["getKeyBtn","Anahtar al","Get a key","Schlüssel holen","Obtenir une clé","Obtener clave","Ottieni chiave","Obter chave","Получить ключ","获取密钥","キーを取得","키 받기"],
  ["enterKeyBtn","Anahtarı gir","Enter key","Schlüssel eingeben","Entrer la clé","Introducir clave","Inserisci chiave","Inserir chave","Ввести ключ","输入密钥","キーを入力","키 입력"],
  ["modeLabel","Çalışma modu","Operating mode","Betriebsmodus","Mode de fonctionnement","Modo de funcionamiento","Modalità operativa","Modo de operação","Режим работы","运行模式","動作モード","작동 모드"],
  ["modeHint","Offline modda transkript ve çeviri tamamen bu bilgisayarda, internetsiz çalışır. Özet ve iyileştirme için yine Groq anahtarı gerekir.","In offline mode, transcription and translation run entirely on this computer without internet. Summaries and polishing still need a Groq key.","Im Offline-Modus laufen Transkription und Übersetzung vollständig auf diesem Computer, ohne Internet. Zusammenfassungen und Überarbeitung benötigen weiterhin einen Groq-Schlüssel.","En mode hors ligne, la transcription et la traduction s'exécutent entièrement sur cet ordinateur, sans internet. Les résumés et l'amélioration nécessitent toujours une clé Groq.","En modo sin conexión, la transcripción y la traducción se ejecutan por completo en este equipo, sin internet. Los resúmenes y la mejora siguen necesitando una clave de Groq.","In modalità offline, trascrizione e traduzione vengono eseguite interamente su questo computer, senza internet. Riepiloghi e miglioramento richiedono comunque una chiave Groq.","No modo offline, a transcrição e a tradução são executadas inteiramente neste computador, sem internet. Resumos e aprimoramento ainda exigem uma chave Groq.","В офлайн-режиме транскрипция и перевод полностью выполняются на этом компьютере без интернета. Для резюме и улучшения по-прежнему нужен ключ Groq.","离线模式下，转录和翻译完全在本机运行，无需联网。摘要和润色仍需要 Groq 密钥。","オフラインモードでは、文字起こしと翻訳がすべてこのコンピューター上でインターネットなしに実行されます。要約と推敲には引き続き Groq キーが必要です。","오프라인 모드에서는 전사와 번역이 인터넷 없이 이 컴퓨터에서 모두 실행됩니다. 요약과 다듬기에는 여전히 Groq 키가 필요합니다."],
  ["modeApi","API (Groq)","API (Groq)","API (Groq)","API (Groq)","API (Groq)","API (Groq)","API (Groq)","API (Groq)","API（Groq）","API（Groq）","API(Groq)"],
  ["modeLocal","Offline (cihazda)","Offline (on-device)","Offline (auf dem Gerät)","Hors ligne (sur l'appareil)","Sin conexión (en el equipo)","Offline (sul dispositivo)","Offline (no dispositivo)","Офлайн (на устройстве)","离线（本机）","オフライン（端末上）","오프라인(기기 내)"],
  ["apiKeyLabel","Groq API anahtarı","Groq API key","Groq-API-Schlüssel","Clé API Groq","Clave API de Groq","Chiave API Groq","Chave de API Groq","API-ключ Groq","Groq API 密钥","Groq APIキー","Groq API 키"],
  ["apiKeyHint","Özet ve başlıklandırma her modda; API modunda transkript ve çeviri de bu anahtarı kullanır. İşletim sisteminin anahtar deposunda şifreli saklanır.","Used for summaries and titling in every mode; in API mode, transcription and translation use it too. Stored encrypted in your operating system's key store.","Wird in jedem Modus für Zusammenfassungen und Titel verwendet; im API-Modus auch für Transkription und Übersetzung. Verschlüsselt im Schlüsselspeicher deines Betriebssystems gespeichert.","Utilisée pour les résumés et les titres dans tous les modes ; en mode API, aussi pour la transcription et la traduction. Stockée chiffrée dans le trousseau de votre système.","Se usa para resúmenes y títulos en todos los modos; en modo API, también para transcripción y traducción. Se guarda cifrada en el almacén de claves del sistema.","Usata per riepiloghi e titoli in ogni modalità; in modalità API anche per trascrizione e traduzione. Salvata cifrata nel portachiavi del sistema.","Usada para resumos e títulos em todos os modos; no modo API, também para transcrição e tradução. Armazenada criptografada no cofre de chaves do sistema.","Используется для резюме и заголовков в любом режиме; в режиме API — также для транскрипции и перевода. Хранится в зашифрованном виде в хранилище ключей ОС.","在任何模式下用于摘要和标题生成；API 模式下也用于转录和翻译。加密保存在操作系统的密钥存储中。","どのモードでも要約とタイトル生成に使用し、APIモードでは文字起こしと翻訳にも使います。OSのキーストアに暗号化して保存されます。","모든 모드에서 요약과 제목 생성에 사용되며, API 모드에서는 전사와 번역에도 사용됩니다. 운영체제 키 저장소에 암호화되어 저장됩니다."],
  ["showBtn","Göster","Show","Anzeigen","Afficher","Mostrar","Mostra","Mostrar","Показать","显示","表示","표시"],
  ["hideBtn","Gizle","Hide","Verbergen","Masquer","Ocultar","Nascondi","Ocultar","Скрыть","隐藏","非表示","숨기기"],
  ["freeKeyLink","Ücretsiz Groq anahtarı al →","Get a free Groq key →","Kostenlosen Groq-Schlüssel holen →","Obtenir une clé Groq gratuite →","Obtener una clave Groq gratis →","Ottieni una chiave Groq gratuita →","Obter uma chave Groq gratuita →","Получить бесплатный ключ Groq →","获取免费的 Groq 密钥 →","無料のGroqキーを取得 →","무료 Groq 키 받기 →"],
  ["saveBtn","Kaydet","Save","Speichern","Enregistrer","Guardar","Salva","Salvar","Сохранить","保存","保存","저장"],
  ["savedStatus","Kaydedildi ✓","Saved ✓","Gespeichert ✓","Enregistré ✓","Guardado ✓","Salvato ✓","Salvo ✓","Сохранено ✓","已保存 ✓","保存しました ✓","저장됨 ✓"],
  ["retryBtn","Tekrar dene","Retry","Erneut versuchen","Réessayer","Reintentar","Riprova","Tentar novamente","Повторить","重试","再試行","다시 시도"],
  ["historyTitle","Geçmiş","History","Verlauf","Historique","Historial","Cronologia","Histórico","История","历史记录","履歴","기록"],
  ["heroTagline","Konuş, anında yazıya dönüşsün.","Speak, and watch it become text instantly.","Sprich, und es wird sofort zu Text.","Parlez, et voyez-le se transformer instantanément en texte.","Habla, y velo convertirse en texto al instante.","Parla, e guardalo trasformarsi in testo all'istante.","Fale, e veja isso virar texto instantaneamente.","Говорите — и это мгновенно превращается в текст.","开口说话，即刻转为文字。","話すだけで、瞬時にテキストに。","말하면 즉시 텍스트로 변환됩니다."],
  ["appendBannerText","\"<strong>{title}</strong>\" kaydına ses ekleniyor. Aşağıdan kaydı yap ya da dosya yükle, otomatik olarak bu kayda eklenecek.","Adding audio to \"<strong>{title}</strong>\". Record or upload a file below and it will be added to this recording automatically.","Audio wird zu „<strong>{title}</strong>\" hinzugefügt. Nimm unten auf oder lade eine Datei hoch — sie wird automatisch hinzugefügt.","Ajout audio à « <strong>{title}</strong> ». Enregistrez ou importez un fichier ci-dessous, il sera automatiquement ajouté.","Añadiendo audio a \"<strong>{title}</strong>\". Graba o sube un archivo abajo y se añadirá automáticamente.","Aggiunta audio a \"<strong>{title}</strong>\". Registra o carica un file qui sotto: verrà aggiunto automaticamente.","Adicionando áudio a \"<strong>{title}</strong>\". Grave ou envie um arquivo abaixo e será adicionado automaticamente.","Добавление аудио к «<strong>{title}</strong>». Запишите или загрузите файл ниже — он будет добавлен автоматически.","正在为\"<strong>{title}</strong>\"添加音频。在下方录音或上传文件，将自动添加到此记录。","「<strong>{title}</strong>」に音声を追加中です。下で録音するかファイルをアップロードすると自動的に追加されます。","\"<strong>{title}</strong>\"에 오디오를 추가하는 중입니다. 아래에서 녹음하거나 파일을 업로드하면 자동으로 추가됩니다."],
  ["cancelBtn","İptal","Cancel","Abbrechen","Annuler","Cancelar","Annulla","Cancelar","Отмена","取消","キャンセル","취소"],
  ["tabMic","Mikrofon","Microphone","Mikrofon","Microphone","Micrófono","Microfono","Microfone","Микрофон","麦克风","マイク","마이크"],
  ["tabUpload","Dosya Yükle","Upload File","Datei hochladen","Importer un fichier","Subir archivo","Carica file","Enviar arquivo","Загрузить файл","上传文件","ファイルをアップロード","파일 업로드"],
  ["recordBtnAria","Kaydı başlat/durdur","Start/stop recording","Aufnahme starten/stoppen","Démarrer/arrêter l'enregistrement","Iniciar/detener grabación","Avvia/ferma registrazione","Iniciar/parar gravação","Начать/остановить запись","开始/停止录音","録音の開始/停止","녹음 시작/중지"],
  ["recordHintIdle","Kaydı başlatmak için tıkla","Click to start recording","Klicken, um die Aufnahme zu starten","Cliquez pour démarrer l'enregistrement","Haz clic para empezar a grabar","Clicca per iniziare la registrazione","Clique para iniciar a gravação","Нажмите, чтобы начать запись","点击开始录音","クリックして録音開始","클릭하여 녹음 시작"],
  ["recordHintRecording","Durdurmak için tıkla","Click to stop","Klicken, um zu stoppen","Cliquez pour arrêter","Haz clic para detener","Clicca per fermare","Clique para parar","Нажмите, чтобы остановить","点击停止","クリックして停止","클릭하여 중지"],
  ["dropzoneText","Ses dosyasını buraya sürükle ya da seç","Drag an audio file here or click to choose","Audiodatei hierher ziehen oder auswählen","Glissez un fichier audio ici ou cliquez pour choisir","Arrastra un archivo de audio aquí o haz clic para elegir","Trascina un file audio qui o clicca per selezionarlo","Arraste um arquivo de áudio aqui ou clique para escolher","Перетащите аудиофайл сюда или нажмите, чтобы выбрать","将音频文件拖到此处或点击选择","音声ファイルをここにドラッグするか、クリックして選択","오디오 파일을 여기로 드래그하거나 클릭하여 선택"],
  ["transcriptHeading","Transkript","Transcript","Transkript","Transcription","Transcripción","Trascrizione","Transcrição","Транскрипт","转录文本","文字起こし","전사 텍스트"],
  ["langPillLabel","Dil","Language","Sprache","Langue","Idioma","Lingua","Idioma","Язык","语言","言語","언어"],
  ["selectPlaceholder","Seç…","Select…","Auswählen…","Choisir…","Seleccionar…","Seleziona…","Selecionar…","Выбрать…","选择…","選択…","선택…"],
  ["translateBtn","Çevir","Translate","Übersetzen","Traduire","Traducir","Traduci","Traduzir","Перевести","翻译","翻訳","번역"],
  ["summarizeBtn","Özetle","Summarize","Zusammenfassen","Résumer","Resumir","Riassumi","Resumir","Резюмировать","总结","要約","요약"],
  ["polishBtn","Başlıklandır & İyileştir","Title & Polish","Titel & Verbessern","Titrer et améliorer","Titular y mejorar","Titola e migliora","Titular e aprimorar","Заголовок и улучшение","生成标题并润色","タイトル生成＆推敲","제목 및 다듬기"],
  ["translationHeading","Çeviri","Translation","Übersetzung","Traduction","Traducción","Traduzione","Tradução","Перевод","翻译","翻訳","번역"],
  ["summaryBadge","✦ Özet","✦ Summary","✦ Zusammenfassung","✦ Résumé","✦ Resumen","✦ Riepilogo","✦ Resumo","✦ Резюме","✦ 摘要","✦ 要約","✦ 요약"],
  ["polishBadge","✎ İyileştirilmiş İçerik","✎ Polished Content","✎ Überarbeiteter Inhalt","✎ Contenu amélioré","✎ Contenido mejorado","✎ Contenuto migliorato","✎ Conteúdo aprimorado","✎ Улучшенный текст","✎ 润色内容","✎ 推敲済みコンテンツ","✎ 다듬어진 콘텐츠"],
  ["statusTranscribing","Transkript oluşturuluyor…","Generating transcript…","Transkript wird erstellt…","Génération de la transcription…","Generando transcripción…","Generazione trascrizione…","Gerando transcrição…","Создание транскрипта…","正在生成转录文本…","文字起こしを生成中…","전사 생성 중…"],
  ["statusDone","Tamamlandı.","Done.","Fertig.","Terminé.","Listo.","Fatto.","Concluído.","Готово.","完成。","完了しました。","완료되었습니다."],
  ["statusGenericError","Bir hata oluştu.","An error occurred.","Ein Fehler ist aufgetreten.","Une erreur s'est produite.","Se produjo un error.","Si è verificato un errore.","Ocorreu um erro.","Произошла ошибка.","发生了错误。","エラーが発生しました。","오류가 발생했습니다."],
  ["statusPickTargetLang","Önce bir hedef dil seç.","Choose a target language first.","Wähle zuerst eine Zielsprache.","Choisissez d'abord une langue cible.","Elige primero un idioma de destino.","Scegli prima una lingua di destinazione.","Escolha primeiro um idioma de destino.","Сначала выберите целевой язык.","请先选择目标语言。","まず対象の言語を選択してください。","먼저 대상 언어를 선택하세요."],
  ["statusAlreadyThisLang","Metin zaten bu dilde.","The text is already in this language.","Der Text ist bereits in dieser Sprache.","Le texte est déjà dans cette langue.","El texto ya está en este idioma.","Il testo è già in questa lingua.","O texto já está neste idioma.","Текст уже на этом языке.","文本已经是该语言。","テキストはすでにこの言語です。","텍스트가 이미 이 언어입니다."],
  ["statusTranslating","Çeviriliyor…","Translating…","Wird übersetzt…","Traduction en cours…","Traduciendo…","Traduzione in corso…","Traduzindo…","Перевод…","正在翻译…","翻訳中…","번역 중…"],
  ["statusTranslateReady","Çeviri hazır.","Translation ready.","Übersetzung ist fertig.","Traduction prête.","Traducción lista.","Traduzione pronta.","Tradução pronta.","Перевод готов.","翻译已完成。","翻訳が完了しました。","번역이 완료되었습니다."],
  ["statusTranslateError","Çeviri hatası.","Translation error.","Übersetzungsfehler.","Erreur de traduction.","Error de traducción.","Errore di traduzione.","Erro de tradução.","Ошибка перевода.","翻译错误。","翻訳エラー。","번역 오류."],
  ["statusSummarizing","Özet oluşturuluyor…","Generating summary…","Zusammenfassung wird erstellt…","Génération du résumé…","Generando resumen…","Generazione riepilogo…","Gerando resumo…","Создание резюме…","正在生成摘要…","要約を生成中…","요약 생성 중…"],
  ["statusSummaryReady","Özet hazır.","Summary ready.","Zusammenfassung ist fertig.","Résumé prêt.","Resumen listo.","Riepilogo pronto.","Resumo pronto.","Резюме готово.","摘要已完成。","要約が完了しました。","요약이 완료되었습니다."],
  ["statusSummaryError","Özetleme hatası.","Summarization error.","Fehler bei der Zusammenfassung.","Erreur de résumé.","Error al resumir.","Errore di riepilogo.","Erro ao resumir.","Ошибка резюмирования.","摘要生成错误。","要約エラー。","요약 오류."],
  ["statusPolishing","İçerik iyileştiriliyor…","Polishing content…","Inhalt wird überarbeitet…","Amélioration du contenu…","Mejorando el contenido…","Miglioramento del contenuto…","Aprimorando o conteúdo…","Улучшение текста…","正在润色内容…","コンテンツを推敲中…","콘텐츠 다듬는 중…"],
  ["statusPolishReady","İyileştirilmiş içerik hazır.","Polished content ready.","Überarbeiteter Inhalt ist fertig.","Contenu amélioré prêt.","Contenido mejorado listo.","Contenuto migliorato pronto.","Conteúdo aprimorado pronto.","Улучшенный текст готов.","润色内容已完成。","推敲済みコンテンツが完了しました。","다듬어진 콘텐츠가 완료되었습니다."],
  ["statusPolishError","İyileştirme hatası.","Polishing error.","Fehler bei der Überarbeitung.","Erreur d'amélioration.","Error al mejorar.","Errore di miglioramento.","Erro ao aprimorar.","Ошибка улучшения.","润色错误。","推敲エラー。","다듬기 오류."],
  ["historyEmptyText","Henüz kayıtlı bir transkript yok. Bir kayıt yaptığında burada görünecek.","No saved transcripts yet. They'll appear here once you make a recording.","Noch keine gespeicherten Transkripte. Sie erscheinen hier nach einer Aufnahme.","Aucune transcription enregistrée. Elles apparaîtront ici après un enregistrement.","Aún no hay transcripciones guardadas. Aparecerán aquí tras una grabación.","Nessuna trascrizione salvata ancora. Appariranno qui dopo una registrazione.","Ainda não há transcrições salvas. Aparecerão aqui após uma gravação.","Пока нет сохранённых транскриптов. Они появятся здесь после записи.","尚无已保存的转录文本。录制后将显示在此处。","保存された文字起こしはまだありません。録音するとここに表示されます。","저장된 전사가 아직 없습니다. 녹음하면 여기에 표시됩니다."],
  ["historyDefaultTitle","Kayıt","Recording","Aufnahme","Enregistrement","Grabación","Registrazione","Gravação","Запись","记录","記録","기록"],
  ["loadBtn","Yükle","Load","Laden","Charger","Cargar","Carica","Carregar","Загрузить","加载","読み込む","불러오기"],
  ["appendBtn","Ses Ekle","Add Audio","Audio hinzufügen","Ajouter de l'audio","Añadir audio","Aggiungi audio","Adicionar áudio","Добавить аудио","添加音频","音声を追加","오디오 추가"],
  ["deleteBtn","Sil","Delete","Löschen","Supprimer","Eliminar","Elimina","Excluir","Удалить","删除","削除","삭제"],
  ["deleteConfirm","\"{title}\" kaydını silmek istediğine emin misin?","Are you sure you want to delete \"{title}\"?","Möchtest du „{title}\" wirklich löschen?","Voulez-vous vraiment supprimer « {title} » ?","¿Seguro que quieres eliminar \"{title}\"?","Sei sicuro di voler eliminare \"{title}\"?","Tem certeza de que deseja excluir \"{title}\"?","Вы уверены, что хотите удалить «{title}»?","确定要删除\"{title}\"吗？","「{title}」を削除してもよろしいですか？","\"{title}\"을(를) 삭제하시겠습니까?"],
  ["statusRecordLoaded","Kayıt yüklendi.","Recording loaded.","Aufnahme geladen.","Enregistrement chargé.","Grabación cargada.","Registrazione caricata.","Gravação carregada.","Запись загружена.","记录已加载。","記録を読み込みました。","기록을 불러왔습니다."],
  ["statusAppendNotFound","Eklenecek kayıt bulunamadı.","The recording to append to was not found.","Die Aufnahme zum Anhängen wurde nicht gefunden.","L'enregistrement auquel ajouter n'a pas été trouvé.","No se encontró la grabación a la que añadir.","Registrazione a cui aggiungere non trovata.","A gravação para adicionar não foi encontrada.","Запись для добавления не найдена.","未找到要追加的记录。","追加先の記録が見つかりません。","추가할 기록을 찾을 수 없습니다."],
  ["statusAppendDone","Ses eklendi, kayıt güncellendi.","Audio added, recording updated.","Audio hinzugefügt, Aufnahme aktualisiert.","Audio ajouté, enregistrement mis à jour.","Audio añadido, grabación actualizada.","Audio aggiunto, registrazione aggiornata.","Áudio adicionado, gravação atualizada.","Аудио добавлено, запись обновлена.","音频已添加，记录已更新。","音声を追加し、記録を更新しました。","오디오가 추가되어 기록이 업데이트되었습니다."],
  ["statusAppendPrompt","\"{title}\" kaydına ses eklemek için kaydı yap ya da dosya yükle.","Record or upload a file to add audio to \"{title}\".","Nimm auf oder lade eine Datei hoch, um Audio zu „{title}\" hinzuzufügen.","Enregistrez ou importez un fichier pour ajouter de l'audio à « {title} ».","Graba o sube un archivo para añadir audio a \"{title}\".","Registra o carica un file per aggiungere audio a \"{title}\".","Grave ou envie um arquivo para adicionar áudio a \"{title}\".","Запишите или загрузите файл, чтобы добавить аудио к «{title}».","录音或上传文件以向\"{title}\"添加音频。","「{title}」に音声を追加するには、録音するかファイルをアップロードしてください。","\"{title}\"에 오디오를 추가하려면 녹음하거나 파일을 업로드하세요."],
  ["micAccessError","Mikrofona erişilemedi: ","Could not access microphone: ","Kein Zugriff auf Mikrofon: ","Impossible d'accéder au microphone : ","No se pudo acceder al micrófono: ","Impossibile accedere al microfono: ","Não foi possível acessar o microfone: ","Не удалось получить доступ к микрофону: ","无法访问麦克风：","マイクにアクセスできませんでした：","마이크에 액세스할 수 없습니다: "],
  ["keyPlainWarning","Bu sistemde güvenli anahtar deposu bulunamadı; anahtar şifrelenmeden saklanacak.","No secure key store was found on this system; the key will be stored unencrypted.","Auf diesem System wurde kein sicherer Schlüsselspeicher gefunden; der Schlüssel wird unverschlüsselt gespeichert.","Aucun trousseau sécurisé trouvé sur ce système ; la clé sera stockée sans chiffrement.","No se encontró un almacén de claves seguro; la clave se guardará sin cifrar.","Nessun portachiavi sicuro trovato; la chiave verrà salvata senza cifratura.","Nenhum cofre seguro foi encontrado; a chave será armazenada sem criptografia.","Безопасное хранилище ключей не найдено; ключ будет сохранён без шифрования.","此系统上未找到安全的密钥存储；密钥将以未加密方式保存。","このシステムには安全なキーストアがないため、キーは暗号化されずに保存されます。","이 시스템에서 보안 키 저장소를 찾지 못해 키가 암호화되지 않고 저장됩니다."],
  ["testKeyBtn","Test et","Test","Testen","Tester","Probar","Verifica","Testar","Проверить","测试","テスト","테스트"],
  ["keyValid","Anahtar geçerli ✓","Key is valid ✓","Schlüssel gültig ✓","Clé valide ✓","Clave válida ✓","Chiave valida ✓","Chave válida ✓","Ключ действителен ✓","密钥有效 ✓","キーは有効です ✓","키가 유효합니다 ✓"],
  ["liveLabel","Canlı yazı","Live text","Live-Text","Texte en direct","Texto en vivo","Testo dal vivo","Texto ao vivo","Живой текст","实时文字","ライブ文字起こし","실시간 텍스트"],
  ["tabSystem","Sistem Sesi","System Audio","Systemaudio","Son système","Audio del sistema","Audio di sistema","Áudio do sistema","Системный звук","系统声音","システム音声","시스템 오디오"],
  ["tabMeeting","Toplantı","Meeting","Meeting","Réunion","Reunión","Riunione","Reunião","Встреча","会议","会議","회의"],
  ["micHint","Mikrofonundan gelen sesi kaydeder.","Records audio from your microphone.","Nimmt Audio von deinem Mikrofon auf.","Enregistre l'audio de votre microphone.","Graba el audio de tu micrófono.","Registra l'audio dal microfono.","Grava o áudio do seu microfone.","Записывает звук с микрофона.","录制麦克风的声音。","マイクの音声を録音します。","마이크 오디오를 녹음합니다."],
  ["systemHint","Bilgisayarda çalan tüm sesleri (toplantı, video, tarayıcı) kaydeder.","Records everything playing on your computer (meetings, videos, browser).","Nimmt alles auf, was auf deinem Computer abgespielt wird (Meetings, Videos, Browser).","Enregistre tout ce qui est lu sur votre ordinateur (réunions, vidéos, navigateur).","Graba todo lo que suena en tu equipo (reuniones, vídeos, navegador).","Registra tutto ciò che viene riprodotto sul computer (riunioni, video, browser).","Grava tudo o que toca no computador (reuniões, vídeos, navegador).","Записывает всё, что воспроизводится на компьютере (встречи, видео, браузер).","录制电脑上播放的所有声音（会议、视频、浏览器）。","コンピューターで再生されるすべての音（会議、動画、ブラウザー）を録音します。","컴퓨터에서 재생되는 모든 소리(회의, 동영상, 브라우저)를 녹음합니다."],
  ["meetingHint","Mikrofonun ve bilgisayar sesi birlikte kaydedilir — online toplantılar için ideal.","Records your microphone and computer audio together — ideal for online meetings.","Nimmt Mikrofon und Computeraudio zusammen auf — ideal für Online-Meetings.","Enregistre votre micro et le son de l'ordinateur ensemble — idéal pour les réunions en ligne.","Graba tu micrófono y el audio del equipo a la vez: ideal para reuniones en línea.","Registra insieme microfono e audio del computer — ideale per le riunioni online.","Grava o microfone e o áudio do computador juntos — ideal para reuniões online.","Записывает микрофон и звук компьютера вместе — идеально для онлайн-встреч.","同时录制麦克风和电脑声音——非常适合线上会议。","マイクとコンピューターの音声を同時に録音します。オンライン会議に最適です。","마이크와 컴퓨터 오디오를 함께 녹음합니다. 온라인 회의에 적합합니다."],
  ["systemAudioMacNote","macOS ilk kullanımda ekran ve sistem sesi kaydı izni ister. İzin verdikten sonra uygulamayı yeniden başlatman gerekebilir.","macOS asks for screen & system audio recording permission on first use. You may need to restart the app after granting it.","macOS fragt bei der ersten Nutzung nach der Berechtigung für Bildschirm- und Systemaudioaufnahme. Danach musst du die App eventuell neu starten.","macOS demande l'autorisation d'enregistrement de l'écran et du son système à la première utilisation. Il peut être nécessaire de redémarrer l'application ensuite.","macOS pide permiso de grabación de pantalla y audio del sistema la primera vez. Puede que tengas que reiniciar la app después.","macOS chiede il permesso di registrazione schermo e audio di sistema al primo utilizzo. Potrebbe essere necessario riavviare l'app.","O macOS pede permissão de gravação de tela e áudio do sistema no primeiro uso. Talvez seja preciso reiniciar o app depois.","При первом использовании macOS запросит разрешение на запись экрана и системного звука. После этого может потребоваться перезапуск приложения.","首次使用时 macOS 会请求屏幕和系统音频录制权限。授权后可能需要重启应用。","初回使用時に macOS が画面とシステム音声の収録許可を求めます。許可後にアプリの再起動が必要な場合があります。","처음 사용할 때 macOS가 화면 및 시스템 오디오 녹음 권한을 요청합니다. 허용 후 앱을 다시 시작해야 할 수 있습니다."],
  ["errSystemAudio","Sistem sesi yakalanamadı. {hint}","Could not capture system audio. {hint}","Systemaudio konnte nicht aufgenommen werden. {hint}","Impossible de capturer le son système. {hint}","No se pudo capturar el audio del sistema. {hint}","Impossibile acquisire l'audio di sistema. {hint}","Não foi possível capturar o áudio do sistema. {hint}","Не удалось захватить системный звук. {hint}","无法捕获系统声音。{hint}","システム音声を取得できませんでした。{hint}","시스템 오디오를 캡처할 수 없습니다. {hint}"],
  ["systemAudioHintMac","Sistem Ayarları › Gizlilik ve Güvenlik › Ekran ve Sistem Sesi Kaydı'ndan YazBunu'ya izin ver. Olmazsa ücretsiz BlackHole sanal ses aygıtını kurup Mikrofon sekmesinde onu seçebilirsin.","Allow YazBunu in System Settings › Privacy & Security › Screen & System Audio Recording. If that fails, install the free BlackHole virtual audio device and select it on the Microphone tab.","Erlaube YazBunu unter Systemeinstellungen › Datenschutz & Sicherheit › Bildschirm- & Systemaudioaufnahme. Falls das nicht hilft, installiere das kostenlose virtuelle Audiogerät BlackHole und wähle es im Mikrofon-Tab.","Autorisez YazBunu dans Réglages Système › Confidentialité et sécurité › Enregistrement de l'écran et de l'audio système. Sinon, installez le périphérique audio virtuel gratuit BlackHole et sélectionnez-le dans l'onglet Microphone.","Permite YazBunu en Ajustes del Sistema › Privacidad y seguridad › Grabación de pantalla y audio del sistema. Si no funciona, instala el dispositivo de audio virtual gratuito BlackHole y selecciónalo en la pestaña Micrófono.","Consenti YazBunu in Impostazioni di Sistema › Privacy e sicurezza › Registrazione schermo e audio di sistema. In alternativa, installa il dispositivo audio virtuale gratuito BlackHole e selezionalo nella scheda Microfono.","Permita o YazBunu em Ajustes do Sistema › Privacidade e Segurança › Gravação de Tela e Áudio do Sistema. Se não funcionar, instale o dispositivo de áudio virtual gratuito BlackHole e selecione-o na aba Microfone.","Разрешите YazBunu в Системных настройках › Конфиденциальность и безопасность › Запись экрана и системного звука. Если не поможет, установите бесплатное виртуальное аудиоустройство BlackHole и выберите его на вкладке «Микрофон».","请在“系统设置 › 隐私与安全性 › 屏幕与系统录音”中允许 YazBunu。如仍不行，可安装免费的 BlackHole 虚拟音频设备，并在“麦克风”标签中选择它。","システム設定 › プライバシーとセキュリティ › 画面とシステムオーディオ録音 で YazBunu を許可してください。うまくいかない場合は無料の仮想オーディオデバイス BlackHole をインストールし、マイクタブで選択してください。","시스템 설정 › 개인정보 보호 및 보안 › 화면 및 시스템 오디오 녹음에서 YazBunu를 허용하세요. 그래도 안 되면 무료 가상 오디오 장치 BlackHole을 설치하고 마이크 탭에서 선택하세요."],
  ["systemAudioHintLinux","PulseAudio veya PipeWire (pipewire-pulse) ve 'parec' komutu gerekli: sudo apt install pulseaudio-utils","PulseAudio or PipeWire (pipewire-pulse) and the 'parec' command are required: sudo apt install pulseaudio-utils","PulseAudio oder PipeWire (pipewire-pulse) und der Befehl 'parec' sind erforderlich: sudo apt install pulseaudio-utils","PulseAudio ou PipeWire (pipewire-pulse) et la commande « parec » sont nécessaires : sudo apt install pulseaudio-utils","Se necesita PulseAudio o PipeWire (pipewire-pulse) y el comando 'parec': sudo apt install pulseaudio-utils","Servono PulseAudio o PipeWire (pipewire-pulse) e il comando 'parec': sudo apt install pulseaudio-utils","É necessário PulseAudio ou PipeWire (pipewire-pulse) e o comando 'parec': sudo apt install pulseaudio-utils","Нужны PulseAudio или PipeWire (pipewire-pulse) и команда «parec»: sudo apt install pulseaudio-utils","需要 PulseAudio 或 PipeWire (pipewire-pulse) 以及 'parec' 命令：sudo apt install pulseaudio-utils","PulseAudio または PipeWire (pipewire-pulse) と 'parec' コマンドが必要です: sudo apt install pulseaudio-utils","PulseAudio 또는 PipeWire(pipewire-pulse)와 'parec' 명령이 필요합니다: sudo apt install pulseaudio-utils"],
  ["systemAudioHintWin","Ses çıkış aygıtının etkin olduğundan emin ol ve tekrar dene.","Make sure an audio output device is enabled and try again.","Stelle sicher, dass ein Audioausgabegerät aktiviert ist, und versuche es erneut.","Vérifiez qu'un périphérique de sortie audio est activé et réessayez.","Asegúrate de que haya un dispositivo de salida de audio activo e inténtalo de nuevo.","Assicurati che un dispositivo di uscita audio sia attivo e riprova.","Verifique se há um dispositivo de saída de áudio ativo e tente novamente.","Убедитесь, что устройство вывода звука включено, и повторите попытку.","请确认已启用音频输出设备，然后重试。","オーディオ出力デバイスが有効か確認して、もう一度お試しください。","오디오 출력 장치가 활성화되어 있는지 확인하고 다시 시도하세요."],
  ["dropzoneHint","ses ve video: wav, mp3, m4a, mp4, webm, ogg, flac…","audio & video: wav, mp3, m4a, mp4, webm, ogg, flac…","Audio & Video: wav, mp3, m4a, mp4, webm, ogg, flac…","audio et vidéo : wav, mp3, m4a, mp4, webm, ogg, flac…","audio y vídeo: wav, mp3, m4a, mp4, webm, ogg, flac…","audio e video: wav, mp3, m4a, mp4, webm, ogg, flac…","áudio e vídeo: wav, mp3, m4a, mp4, webm, ogg, flac…","аудио и видео: wav, mp3, m4a, mp4, webm, ogg, flac…","音频和视频：wav、mp3、m4a、mp4、webm、ogg、flac…","音声・動画: wav、mp3、m4a、mp4、webm、ogg、flac…","오디오 및 동영상: wav, mp3, m4a, mp4, webm, ogg, flac…"],
  ["stageDecode","Ses hazırlanıyor…","Preparing audio…","Audio wird vorbereitet…","Préparation de l'audio…","Preparando el audio…","Preparazione audio…","Preparando o áudio…","Подготовка аудио…","正在准备音频…","音声を準備中…","오디오 준비 중…"],
  ["stageDiarize","Konuşmacılar ayrılıyor…","Separating speakers…","Sprecher werden getrennt…","Séparation des locuteurs…","Separando hablantes…","Separazione dei parlanti…","Separando locutores…","Разделение говорящих…","正在区分说话人…","話者を分離中…","화자 분리 중…"],
  ["stageWait","Groq kota sınırı — {s} sn bekleniyor…","Groq rate limit — waiting {s}s…","Groq-Limit — warte {s} s…","Limite Groq — attente de {s} s…","Límite de Groq — esperando {s} s…","Limite Groq — attesa di {s} s…","Limite do Groq — aguardando {s} s…","Лимит Groq — ожидание {s} с…","Groq 速率限制——等待 {s} 秒…","Groq のレート制限 — {s} 秒待機中…","Groq 사용량 제한 — {s}초 대기 중…"],
  ["stageLoad","Model yükleniyor…","Loading model…","Modell wird geladen…","Chargement du modèle…","Cargando modelo…","Caricamento modello…","Carregando modelo…","Загрузка модели…","正在加载模型…","モデルを読み込み中…","모델 불러오는 중…"],
  ["stageDownload","Model indiriliyor…","Downloading model…","Modell wird heruntergeladen…","Téléchargement du modèle…","Descargando modelo…","Download del modello…","Baixando modelo…","Загрузка модели из сети…","正在下载模型…","モデルをダウンロード中…","모델 다운로드 중…"],
  ["stageExtract","Model açılıyor…","Unpacking model…","Modell wird entpackt…","Décompression du modèle…","Descomprimiendo modelo…","Estrazione del modello…","Descompactando modelo…","Распаковка модели…","正在解压模型…","モデルを展開中…","모델 압축 해제 중…"],
  ["statusCancelled","İptal edildi.","Cancelled.","Abgebrochen.","Annulé.","Cancelado.","Annullato.","Cancelado.","Отменено.","已取消。","キャンセルしました。","취소되었습니다."],
  ["liveListening","Dinleniyor… metin konuştukça burada belirecek.","Listening… text will appear here as you speak.","Hört zu… der Text erscheint hier beim Sprechen.","Écoute… le texte apparaîtra ici au fil de la parole.","Escuchando… el texto aparecerá aquí mientras hablas.","In ascolto… il testo apparirà qui mentre parli.","Ouvindo… o texto aparecerá aqui enquanto você fala.","Слушаю… текст появится здесь по ходу речи.","正在聆听……说话时文字会出现在这里。","聞き取り中… 話すとここにテキストが表示されます。","듣는 중… 말하는 대로 여기에 텍스트가 나타납니다."],
  ["livePending","{s} sn işleniyor…","Processing {s}s…","{s} s werden verarbeitet…","Traitement de {s} s…","Procesando {s} s…","Elaborazione di {s} s…","Processando {s} s…","Обработка {s} с…","正在处理 {s} 秒…","{s} 秒分を処理中…","{s}초 처리 중…"],
  ["statusFinishing","Kayıt tamamlanıyor…","Finishing recording…","Aufnahme wird abgeschlossen…","Finalisation de l'enregistrement…","Finalizando la grabación…","Completamento registrazione…","Finalizando a gravação…","Завершение записи…","正在完成录音…","録音を仕上げ中…","녹음 마무리 중…"],
  ["copyBtn","Kopyala","Copy","Kopieren","Copier","Copiar","Copia","Copiar","Копировать","复制","コピー","복사"],
  ["copiedStatus","Panoya kopyalandı ✓","Copied to clipboard ✓","In die Zwischenablage kopiert ✓","Copié dans le presse-papiers ✓","Copiado al portapapeles ✓","Copiato negli appunti ✓","Copiado para a área de transferência ✓","Скопировано в буфер обмена ✓","已复制到剪贴板 ✓","クリップボードにコピーしました ✓","클립보드에 복사됨 ✓"],
  ["editBtn","Düzenle","Edit","Bearbeiten","Modifier","Editar","Modifica","Editar","Изменить","编辑","編集","편집"],
  ["doneBtn","Bitti","Done","Fertig","Terminé","Listo","Fatto","Concluído","Готово","完成","完了","완료"],
  ["editHint","Segment metinlerini düzenleyebilir, konuşmacı adına tıklayıp isim verebilirsin.","You can edit segment text and click a speaker name to rename it.","Du kannst Segmenttexte bearbeiten und auf einen Sprechernamen klicken, um ihn umzubenennen.","Vous pouvez modifier le texte des segments et cliquer sur un locuteur pour le renommer.","Puedes editar el texto de los segmentos y hacer clic en un hablante para renombrarlo.","Puoi modificare il testo dei segmenti e cliccare su un parlante per rinominarlo.","Você pode editar o texto dos segmentos e clicar em um locutor para renomeá-lo.","Можно редактировать текст сегментов и нажать на имя говорящего, чтобы переименовать его.","你可以编辑片段文本，并点击说话人名称为其重命名。","セグメントのテキストを編集でき、話者名をクリックすると名前を変更できます。","세그먼트 텍스트를 편집하고 화자 이름을 클릭해 이름을 바꿀 수 있습니다."],
  ["speakersHeading","Konuşmacılar","Speakers","Sprecher","Locuteurs","Hablantes","Parlanti","Locutores","Говорящие","说话人","話者","화자"],
  ["speakerDefault","Konuşmacı {n}","Speaker {n}","Sprecher {n}","Locuteur {n}","Hablante {n}","Parlante {n}","Locutor {n}","Говорящий {n}","说话人 {n}","話者 {n}","화자 {n}"],
  ["renamePrompt","Bu konuşmacının adı:","Name for this speaker:","Name dieses Sprechers:","Nom de ce locuteur :","Nombre de este hablante:","Nome di questo parlante:","Nome deste locutor:","Имя этого говорящего:","该说话人的名称：","この話者の名前：","이 화자의 이름:"],
  ["segmentsHeading","Zaman Damgalı Segmentler","Timestamped Segments","Segmente mit Zeitstempel","Segments horodatés","Segmentos con marca de tiempo","Segmenti con marca temporale","Segmentos com carimbo de tempo","Сегменты с метками времени","带时间戳的片段","タイムスタンプ付きセグメント","타임스탬프 세그먼트"],
  ["exportLabel","Dışa aktar","Export","Exportieren","Exporter","Exportar","Esporta","Exportar","Экспорт","导出","エクスポート","내보내기"],
  ["statusExported","Kaydedildi: {file}","Saved: {file}","Gespeichert: {file}","Enregistré : {file}","Guardado: {file}","Salvato: {file}","Salvo: {file}","Сохранено: {file}","已保存：{file}","保存しました: {file}","저장됨: {file}"],
  ["playAria","Oynat / duraklat","Play / pause","Abspielen / Pause","Lecture / pause","Reproducir / pausar","Riproduci / pausa","Reproduzir / pausar","Воспроизвести / пауза","播放 / 暂停","再生 / 一時停止","재생 / 일시정지"],
  ["settingsGeneral","Genel","General","Allgemein","Général","General","Generale","Geral","Общие","常规","一般","일반"],
  ["settingsTranscription","Transkript","Transcription","Transkription","Transcription","Transcripción","Trascrizione","Transcrição","Транскрипция","转录","文字起こし","전사"],
  ["settingsAdvanced","Gelişmiş","Advanced","Erweitert","Avancé","Avanzado","Avanzate","Avançado","Дополнительно","高级","詳細","고급"],
  ["localModelLabel","Offline Whisper modeli","Offline Whisper model","Offline-Whisper-Modell","Modèle Whisper hors ligne","Modelo Whisper sin conexión","Modello Whisper offline","Modelo Whisper offline","Офлайн-модель Whisper","离线 Whisper 模型","オフライン Whisper モデル","오프라인 Whisper 모델"],
  ["localModelHint","Büyük model daha doğru ama daha yavaştır. Model ilk kullanımda bir kez indirilir.","Larger models are more accurate but slower. The model is downloaded once on first use.","Größere Modelle sind genauer, aber langsamer. Das Modell wird beim ersten Mal einmalig heruntergeladen.","Les grands modèles sont plus précis mais plus lents. Le modèle est téléchargé une seule fois.","Los modelos grandes son más precisos pero más lentos. El modelo se descarga una sola vez.","I modelli grandi sono più precisi ma più lenti. Il modello viene scaricato una sola volta.","Modelos maiores são mais precisos, porém mais lentos. O modelo é baixado uma única vez.","Большие модели точнее, но медленнее. Модель скачивается один раз.","模型越大越准确，但速度越慢。模型仅在首次使用时下载一次。","大きいモデルほど正確ですが遅くなります。モデルは初回に一度だけダウンロードされます。","큰 모델일수록 정확하지만 느립니다. 모델은 처음 한 번만 다운로드됩니다."],
  ["modelTiny","Tiny — en hızlı","Tiny — fastest","Tiny — am schnellsten","Tiny — le plus rapide","Tiny — el más rápido","Tiny — il più veloce","Tiny — o mais rápido","Tiny — самая быстрая","Tiny — 最快","Tiny — 最速","Tiny — 가장 빠름"],
  ["modelSmall","Small — dengeli","Small — balanced","Small — ausgewogen","Small — équilibré","Small — equilibrado","Small — bilanciato","Small — equilibrado","Small — сбалансированная","Small — 均衡","Small — バランス型","Small — 균형"],
  ["modelTurbo","Turbo — önerilen","Turbo — recommended","Turbo — empfohlen","Turbo — recommandé","Turbo — recomendado","Turbo — consigliato","Turbo — recomendado","Turbo — рекомендуется","Turbo — 推荐","Turbo — おすすめ","Turbo — 권장"],
  ["modelLarge","Large-v3 — en doğru, en yavaş","Large-v3 — most accurate, slowest","Large-v3 — am genauesten, am langsamsten","Large-v3 — le plus précis, le plus lent","Large-v3 — el más preciso y lento","Large-v3 — il più preciso, il più lento","Large-v3 — o mais preciso e lento","Large-v3 — самая точная и медленная","Large-v3 — 最准确、最慢","Large-v3 — 最も正確・最も低速","Large-v3 — 가장 정확, 가장 느림"],
  ["modelInstalled","İndirildi","Downloaded","Heruntergeladen","Téléchargé","Descargado","Scaricato","Baixado","Загружено","已下载","ダウンロード済み","다운로드됨"],
  ["modelDownloadBtn","İndir","Download","Herunterladen","Télécharger","Descargar","Scarica","Baixar","Скачать","下载","ダウンロード","다운로드"],
  ["translateModelLabel","Offline çeviri modeli (NLLB-200)","Offline translation model (NLLB-200)","Offline-Übersetzungsmodell (NLLB-200)","Modèle de traduction hors ligne (NLLB-200)","Modelo de traducción sin conexión (NLLB-200)","Modello di traduzione offline (NLLB-200)","Modelo de tradução offline (NLLB-200)","Офлайн-модель перевода (NLLB-200)","离线翻译模型（NLLB-200）","オフライン翻訳モデル（NLLB-200）","오프라인 번역 모델(NLLB-200)"],
  ["transcriptionLanguageLabel","Konuşma dili","Spoken language","Gesprochene Sprache","Langue parlée","Idioma hablado","Lingua parlata","Idioma falado","Язык речи","说话语言","話している言語","음성 언어"],
  ["transcriptionLanguageHint","Kısa kayıtlarda dili sabitlemek tanıma doğruluğunu artırır.","Fixing the language improves accuracy on short recordings.","Eine feste Sprache verbessert die Genauigkeit bei kurzen Aufnahmen.","Fixer la langue améliore la précision sur les enregistrements courts.","Fijar el idioma mejora la precisión en grabaciones cortas.","Fissare la lingua migliora la precisione nelle registrazioni brevi.","Fixar o idioma melhora a precisão em gravações curtas.","Фиксированный язык повышает точность на коротких записях.","固定语言可提高短录音的识别准确率。","言語を固定すると短い録音での精度が上がります。","언어를 고정하면 짧은 녹음의 정확도가 높아집니다."],
  ["autoDetect","Otomatik algıla","Auto-detect","Automatisch erkennen","Détection automatique","Detección automática","Rilevamento automatico","Detecção automática","Автоопределение","自动检测","自動検出","자동 감지"],
  ["numSpeakersLabel","Konuşmacı sayısı","Number of speakers","Anzahl der Sprecher","Nombre de locuteurs","Número de hablantes","Numero di parlanti","Número de locutores","Количество говорящих","说话人数","話者の人数","화자 수"],
  ["numSpeakersHint","Biliyorsan sayıyı seçmek konuşmacı ayrımını belirgin şekilde iyileştirir.","If you know it, choosing the count noticeably improves speaker separation.","Wenn du sie kennst, verbessert die Angabe der Anzahl die Sprechertrennung deutlich.","Si vous le connaissez, indiquer le nombre améliore nettement la séparation.","Si lo sabes, elegir el número mejora notablemente la separación.","Se lo conosci, indicare il numero migliora molto la separazione.","Se você souber, escolher o número melhora bastante a separação.","Если знаете число, укажите его — разделение станет заметно точнее.","如果知道人数，选择它能显著改善说话人区分效果。","人数がわかっている場合は選ぶと話者分離の精度が大きく向上します。","알고 있다면 수를 선택하면 화자 분리가 크게 개선됩니다."],
  ["keepAudioLabel","Ses kayıtlarını sakla","Keep audio recordings","Audioaufnahmen behalten","Conserver les enregistrements audio","Conservar las grabaciones de audio","Conserva le registrazioni audio","Manter as gravações de áudio","Сохранять аудиозаписи","保留录音文件","録音音声を保存","오디오 녹음 보관"],
  ["keepAudioHint","Geçmişte dinleyebilir; sonradan ses eklediğinde konuşmacılar baştan doğru ayrılır.","Lets you play recordings back; when you add audio later, speakers are re-separated correctly.","Ermöglicht die Wiedergabe; beim späteren Hinzufügen von Audio werden Sprecher korrekt neu getrennt.","Permet la réécoute ; en ajoutant de l'audio plus tard, les locuteurs sont correctement re-séparés.","Permite volver a escuchar; al añadir audio después, los hablantes se vuelven a separar correctamente.","Permette il riascolto; aggiungendo audio in seguito, i parlanti vengono separati di nuovo correttamente.","Permite ouvir novamente; ao adicionar áudio depois, os locutores são separados de novo corretamente.","Позволяет прослушивать записи; при добавлении аудио позже говорящие разделяются заново.","可回放录音；之后追加音频时会重新正确区分说话人。","録音を再生でき、後から音声を追加すると話者が正しく再分離されます。","녹음을 다시 들을 수 있고, 나중에 오디오를 추가하면 화자가 올바르게 다시 분리됩니다."],
  ["micDeviceLabel","Mikrofon","Microphone","Mikrofon","Microphone","Micrófono","Microfono","Microfone","Микрофон","麦克风","マイク","마이크"],
  ["defaultDevice","Sistem varsayılanı","System default","Systemstandard","Par défaut du système","Predeterminado del sistema","Predefinito di sistema","Padrão do sistema","По умолчанию","系统默认","システムの既定","시스템 기본값"],
  ["shortcutLabel","Kayıt kısayolu","Recording shortcut","Aufnahme-Tastenkürzel","Raccourci d'enregistrement","Atajo de grabación","Scorciatoia di registrazione","Atalho de gravação","Сочетание для записи","录音快捷键","録音ショートカット","녹음 단축키"],
  ["shortcutHint","Uygulama arka plandayken bile kaydı başlatır/durdurur. Boş bırakırsan kapanır.","Starts/stops recording even when the app is in the background. Leave empty to disable.","Startet/stoppt die Aufnahme auch im Hintergrund. Leer lassen zum Deaktivieren.","Démarre/arrête l'enregistrement même en arrière-plan. Laissez vide pour désactiver.","Inicia/detiene la grabación incluso en segundo plano. Déjalo vacío para desactivarlo.","Avvia/ferma la registrazione anche in background. Lascia vuoto per disattivare.","Inicia/para a gravação mesmo em segundo plano. Deixe vazio para desativar.","Запускает/останавливает запись даже в фоне. Оставьте пустым, чтобы отключить.","即使应用在后台也能开始/停止录音。留空则禁用。","アプリがバックグラウンドでも録音を開始/停止します。空欄で無効になります。","앱이 백그라운드에 있어도 녹음을 시작/중지합니다. 비워 두면 비활성화됩니다."],
  ["shortcutInvalid","Bu kısayol kullanılamıyor (başka bir uygulama kullanıyor olabilir).","This shortcut can't be used (another app may be using it).","Dieses Tastenkürzel ist nicht verfügbar (evtl. von einer anderen App belegt).","Ce raccourci est indisponible (une autre application l'utilise peut-être).","Este atajo no se puede usar (puede que otra app lo esté usando).","Questa scorciatoia non è utilizzabile (forse è usata da un'altra app).","Este atalho não pode ser usado (outro app pode estar usando).","Это сочетание недоступно (возможно, занято другим приложением).","此快捷键不可用（可能已被其他应用占用）。","このショートカットは使用できません（他のアプリが使用中の可能性があります）。","이 단축키는 사용할 수 없습니다(다른 앱이 사용 중일 수 있음)."],
  ["closeToTrayLabel","Pencereyi kapatınca tepside çalışmaya devam et","Keep running in the tray when the window is closed","Beim Schließen im Infobereich weiterlaufen","Continuer dans la barre système à la fermeture","Seguir en la bandeja al cerrar la ventana","Continua nell'area di notifica alla chiusura","Continuar na bandeja ao fechar a janela","Продолжать работу в трее при закрытии окна","关闭窗口后在托盘中继续运行","ウィンドウを閉じてもトレイで動作を続ける","창을 닫아도 트레이에서 계속 실행"],
  ["checkUpdatesLabel","Güncellemeleri denetle","Check for updates","Nach Updates suchen","Rechercher les mises à jour","Buscar actualizaciones","Controlla aggiornamenti","Verificar atualizações","Проверять обновления","检查更新","アップデートを確認","업데이트 확인"],
  ["groqModelsLabel","Groq modelleri","Groq models","Groq-Modelle","Modèles Groq","Modelos de Groq","Modelli Groq","Modelos Groq","Модели Groq","Groq 模型","Groq モデル","Groq 모델"],
  ["groqModelsHint","Groq bir modeli kaldırırsa buradan güncel kimliği girebilirsin (console.groq.com/docs/models).","If Groq retires a model, enter the current ID here (console.groq.com/docs/models).","Wenn Groq ein Modell entfernt, gib hier die aktuelle ID ein (console.groq.com/docs/models).","Si Groq retire un modèle, saisissez ici l'identifiant actuel (console.groq.com/docs/models).","Si Groq retira un modelo, introduce aquí el ID actual (console.groq.com/docs/models).","Se Groq ritira un modello, inserisci qui l'ID attuale (console.groq.com/docs/models).","Se o Groq remover um modelo, insira aqui o ID atual (console.groq.com/docs/models).","Если Groq удалит модель, укажите здесь актуальный ID (console.groq.com/docs/models).","如果 Groq 下线了某个模型，可在此填写当前 ID（console.groq.com/docs/models）。","Groq がモデルを廃止した場合は、ここに現在の ID を入力してください（console.groq.com/docs/models）。","Groq가 모델을 종료하면 여기에 현재 ID를 입력하세요(console.groq.com/docs/models)."],
  ["transcribeModelLabel","Transkript","Transcription","Transkription","Transcription","Transcripción","Trascrizione","Transcrição","Транскрипция","转录","文字起こし","전사"],
  ["llmModelLabel","Özet / iyileştirme / çeviri","Summary / polish / translation","Zusammenfassung / Überarbeitung / Übersetzung","Résumé / amélioration / traduction","Resumen / mejora / traducción","Riepilogo / miglioramento / traduzione","Resumo / aprimoramento / tradução","Резюме / улучшение / перевод","摘要 / 润色 / 翻译","要約 / 推敲 / 翻訳","요약 / 다듬기 / 번역"],
  ["openDataFolder","Veri klasörünü aç","Open data folder","Datenordner öffnen","Ouvrir le dossier de données","Abrir carpeta de datos","Apri cartella dati","Abrir pasta de dados","Открыть папку данных","打开数据文件夹","データフォルダーを開く","데이터 폴더 열기"],
  ["searchPlaceholder","Geçmişte ara…","Search history…","Verlauf durchsuchen…","Rechercher dans l'historique…","Buscar en el historial…","Cerca nella cronologia…","Pesquisar no histórico…","Поиск по истории…","搜索历史记录…","履歴を検索…","기록 검색…"],
  ["historyNoMatch","Eşleşen kayıt yok.","No matching recordings.","Keine passenden Aufnahmen.","Aucun enregistrement correspondant.","No hay grabaciones que coincidan.","Nessuna registrazione corrispondente.","Nenhuma gravação correspondente.","Совпадений нет.","没有匹配的记录。","一致する記録はありません。","일치하는 기록이 없습니다."],
  ["errNoApiKey","Groq API anahtarı gerekli. Ayarlar'dan anahtarını gir.","A Groq API key is required. Enter it in Settings.","Ein Groq-API-Schlüssel ist erforderlich. Gib ihn in den Einstellungen ein.","Une clé API Groq est requise. Saisissez-la dans les Paramètres.","Se necesita una clave API de Groq. Introdúcela en Ajustes.","Serve una chiave API Groq. Inseriscila nelle Impostazioni.","É necessária uma chave de API Groq. Insira-a nas Configurações.","Нужен API-ключ Groq. Введите его в настройках.","需要 Groq API 密钥，请在设置中输入。","Groq API キーが必要です。設定で入力してください。","Groq API 키가 필요합니다. 설정에서 입력하세요."],
  ["errInvalidKey","Groq anahtarı geçersiz veya yetkisiz. Ayarlar'dan kontrol et.","The Groq key is invalid or unauthorized. Check it in Settings.","Der Groq-Schlüssel ist ungültig oder nicht berechtigt. Prüfe ihn in den Einstellungen.","La clé Groq est invalide ou non autorisée. Vérifiez-la dans les Paramètres.","La clave de Groq no es válida o no está autorizada. Revísala en Ajustes.","La chiave Groq non è valida o non è autorizzata. Controllala nelle Impostazioni.","A chave Groq é inválida ou não autorizada. Verifique nas Configurações.","Ключ Groq недействителен или не авторизован. Проверьте его в настройках.","Groq 密钥无效或未授权，请在设置中检查。","Groq キーが無効か権限がありません。設定を確認してください。","Groq 키가 잘못되었거나 권한이 없습니다. 설정에서 확인하세요."],
  ["errRateLimit","Groq ücretsiz kota sınırına ulaşıldı. Birkaç dakika sonra tekrar dene.","Groq's free quota was reached. Try again in a few minutes.","Das kostenlose Groq-Kontingent ist erschöpft. Versuche es in ein paar Minuten erneut.","Le quota gratuit de Groq est atteint. Réessayez dans quelques minutes.","Se alcanzó la cuota gratuita de Groq. Inténtalo de nuevo en unos minutos.","Quota gratuita di Groq raggiunta. Riprova tra qualche minuto.","A cota gratuita do Groq foi atingida. Tente novamente em alguns minutos.","Бесплатная квота Groq исчерпана. Повторите через несколько минут.","已达到 Groq 免费额度上限，请几分钟后再试。","Groq の無料枠の上限に達しました。数分後に再試行してください。","Groq 무료 할당량에 도달했습니다. 몇 분 후 다시 시도하세요."],
  ["errNetwork","Groq'a bağlanılamadı. İnternet bağlantını kontrol et.","Could not reach Groq. Check your internet connection.","Groq ist nicht erreichbar. Prüfe deine Internetverbindung.","Impossible de joindre Groq. Vérifiez votre connexion internet.","No se pudo conectar con Groq. Revisa tu conexión a internet.","Impossibile raggiungere Groq. Controlla la connessione.","Não foi possível conectar ao Groq. Verifique sua conexão.","Не удалось подключиться к Groq. Проверьте интернет-соединение.","无法连接 Groq，请检查网络连接。","Groq に接続できません。インターネット接続を確認してください。","Groq에 연결할 수 없습니다. 인터넷 연결을 확인하세요."],
  ["errGroq","Groq hatası: {detail}","Groq error: {detail}","Groq-Fehler: {detail}","Erreur Groq : {detail}","Error de Groq: {detail}","Errore Groq: {detail}","Erro do Groq: {detail}","Ошибка Groq: {detail}","Groq 错误：{detail}","Groq エラー: {detail}","Groq 오류: {detail}"],
  ["errModelGone","Groq modeli kullanılamıyor ({detail}). Ayarlar › Gelişmiş'ten güncel model kimliğini gir.","The Groq model is unavailable ({detail}). Enter a current model ID in Settings › Advanced.","Das Groq-Modell ist nicht verfügbar ({detail}). Gib unter Einstellungen › Erweitert eine aktuelle Modell-ID ein.","Le modèle Groq est indisponible ({detail}). Saisissez un identifiant actuel dans Paramètres › Avancé.","El modelo de Groq no está disponible ({detail}). Introduce un ID actual en Ajustes › Avanzado.","Il modello Groq non è disponibile ({detail}). Inserisci un ID aggiornato in Impostazioni › Avanzate.","O modelo do Groq não está disponível ({detail}). Insira um ID atual em Configurações › Avançado.","Модель Groq недоступна ({detail}). Укажите актуальный ID в Настройки › Дополнительно.","Groq 模型不可用（{detail}）。请在“设置 › 高级”中填写当前模型 ID。","Groq モデルが利用できません（{detail}）。設定 › 詳細 で現在のモデル ID を入力してください。","Groq 모델을 사용할 수 없습니다({detail}). 설정 › 고급에서 현재 모델 ID를 입력하세요."],
  ["errDecode","Ses dosyası okunamadı. Dosya bozuk ya da desteklenmeyen bir format olabilir.","The audio file could not be read. It may be corrupt or in an unsupported format.","Die Audiodatei konnte nicht gelesen werden. Sie ist evtl. beschädigt oder hat ein nicht unterstütztes Format.","Le fichier audio est illisible. Il est peut-être corrompu ou dans un format non pris en charge.","No se pudo leer el archivo de audio. Puede estar dañado o en un formato no compatible.","Impossibile leggere il file audio. Potrebbe essere danneggiato o in un formato non supportato.","Não foi possível ler o arquivo de áudio. Ele pode estar corrompido ou em formato não suportado.","Не удалось прочитать аудиофайл. Возможно, он повреждён или формат не поддерживается.","无法读取音频文件，文件可能已损坏或格式不受支持。","音声ファイルを読み込めませんでした。破損しているか、未対応の形式の可能性があります。","오디오 파일을 읽을 수 없습니다. 손상되었거나 지원되지 않는 형식일 수 있습니다."],
  ["errNoSpeech","Kayıtta konuşma algılanmadı.","No speech was detected in the recording.","In der Aufnahme wurde keine Sprache erkannt.","Aucune parole détectée dans l'enregistrement.","No se detectó voz en la grabación.","Nessun parlato rilevato nella registrazione.","Nenhuma fala detectada na gravação.","В записи не обнаружена речь.","录音中未检测到语音。","録音から音声が検出されませんでした。","녹음에서 음성이 감지되지 않았습니다."],
  ["errDiarize","Konuşmacı ayrımı başarısız oldu, transkript konuşmacısız kaydedildi. ({detail})","Speaker separation failed; the transcript was saved without speakers. ({detail})","Die Sprechertrennung ist fehlgeschlagen; das Transkript wurde ohne Sprecher gespeichert. ({detail})","La séparation des locuteurs a échoué ; la transcription a été enregistrée sans locuteurs. ({detail})","La separación de hablantes falló; la transcripción se guardó sin hablantes. ({detail})","La separazione dei parlanti non è riuscita; la trascrizione è stata salvata senza parlanti. ({detail})","A separação de locutores falhou; a transcrição foi salva sem locutores. ({detail})","Не удалось разделить говорящих; транскрипт сохранён без них. ({detail})","说话人区分失败，转录已在无说话人信息的情况下保存。（{detail}）","話者分離に失敗したため、話者なしで文字起こしを保存しました。（{detail}）","화자 분리에 실패하여 화자 없이 전사를 저장했습니다. ({detail})"],
  ["errModelDownload","Model indirilemedi. İnternet bağlantını kontrol edip tekrar dene.","The model could not be downloaded. Check your internet connection and try again.","Das Modell konnte nicht heruntergeladen werden. Prüfe die Verbindung und versuche es erneut.","Le modèle n'a pas pu être téléchargé. Vérifiez votre connexion et réessayez.","No se pudo descargar el modelo. Revisa tu conexión e inténtalo de nuevo.","Impossibile scaricare il modello. Controlla la connessione e riprova.","Não foi possível baixar o modelo. Verifique sua conexão e tente novamente.","Не удалось скачать модель. Проверьте подключение и повторите попытку.","模型下载失败，请检查网络连接后重试。","モデルをダウンロードできませんでした。接続を確認して再試行してください。","모델을 다운로드할 수 없습니다. 연결을 확인하고 다시 시도하세요."],
  ["errLocalAsr","Offline transkript başarısız: {detail}","Offline transcription failed: {detail}","Offline-Transkription fehlgeschlagen: {detail}","Échec de la transcription hors ligne : {detail}","Falló la transcripción sin conexión: {detail}","Trascrizione offline non riuscita: {detail}","Falha na transcrição offline: {detail}","Ошибка офлайн-транскрипции: {detail}","离线转录失败：{detail}","オフライン文字起こしに失敗しました: {detail}","오프라인 전사 실패: {detail}"],
  ["errUnknown","Beklenmeyen hata: {detail}","Unexpected error: {detail}","Unerwarteter Fehler: {detail}","Erreur inattendue : {detail}","Error inesperado: {detail}","Errore imprevisto: {detail}","Erro inesperado: {detail}","Непредвиденная ошибка: {detail}","意外错误：{detail}","予期しないエラー: {detail}","예기치 않은 오류: {detail}"],
  ["errBusy","Başka bir işlem sürüyor, bitmesini bekle.","Another task is running, please wait for it to finish.","Ein anderer Vorgang läuft, bitte warte, bis er fertig ist.","Une autre tâche est en cours, veuillez patienter.","Hay otra tarea en curso; espera a que termine.","È in corso un'altra operazione, attendi che finisca.","Outra tarefa está em andamento; aguarde a conclusão.","Выполняется другая задача, дождитесь её завершения.","另一项任务正在进行，请等待其完成。","別の処理が実行中です。完了までお待ちください。","다른 작업이 진행 중입니다. 끝날 때까지 기다려 주세요."],
  ["trayShow","YazBunu'yu göster","Show YazBunu","YazBunu anzeigen","Afficher YazBunu","Mostrar YazBunu","Mostra YazBunu","Mostrar YazBunu","Показать YazBunu","显示 YazBunu","YazBunu を表示","YazBunu 표시"],
  ["trayRecord","Kaydı başlat","Start recording","Aufnahme starten","Démarrer l'enregistrement","Iniciar grabación","Avvia registrazione","Iniciar gravação","Начать запись","开始录音","録音を開始","녹음 시작"],
  ["trayStop","Kaydı durdur","Stop recording","Aufnahme stoppen","Arrêter l'enregistrement","Detener grabación","Ferma registrazione","Parar gravação","Остановить запись","停止录音","録音を停止","녹음 중지"],
  ["trayQuit","Çıkış","Quit","Beenden","Quitter","Salir","Esci","Sair","Выход","退出","終了","종료"],
  ["notifyDoneTitle","Transkript hazır","Transcript ready","Transkript fertig","Transcription prête","Transcripción lista","Trascrizione pronta","Transcrição pronta","Транскрипт готов","转录已完成","文字起こし完了","전사 완료"],
  ["quitWhileRecording","Kayıt sürüyor. Çıkarsan bu kayıt kaybolur. Yine de çıkılsın mı?","A recording is in progress. Quitting will discard it. Quit anyway?","Eine Aufnahme läuft. Beim Beenden geht sie verloren. Trotzdem beenden?","Un enregistrement est en cours. Quitter le supprimera. Quitter quand même ?","Hay una grabación en curso. Si sales, se perderá. ¿Salir de todos modos?","È in corso una registrazione. Uscendo andrà persa. Uscire comunque?","Há uma gravação em andamento. Sair irá descartá-la. Sair mesmo assim?","Идёт запись. При выходе она будет потеряна. Всё равно выйти?","正在录音。退出将丢失此录音。仍要退出吗？","録音中です。終了すると録音は失われます。終了しますか？","녹음 중입니다. 종료하면 녹음이 사라집니다. 그래도 종료할까요?"],
  ["updateAvailable","Yeni sürüm mevcut: {v}","New version available: {v}","Neue Version verfügbar: {v}","Nouvelle version disponible : {v}","Nueva versión disponible: {v}","Nuova versione disponibile: {v}","Nova versão disponível: {v}","Доступна новая версия: {v}","有新版本：{v}","新しいバージョンがあります: {v}","새 버전 사용 가능: {v}"],
  ["updateDownloadBtn","İndir","Download","Herunterladen","Télécharger","Descargar","Scarica","Baixar","Скачать","下载","ダウンロード","다운로드"],
  ["outputLangAuto","Transkript dili","Transcript language","Sprache des Transkripts","Langue de la transcription","Idioma de la transcripción","Lingua della trascrizione","Idioma da transcrição","Язык транскрипта","转录语言","文字起こしの言語","전사 언어"],
  ["themeLabel","Tema","Theme","Design","Thème","Tema","Tema","Tema","Тема","主题","テーマ","테마"],
  ["themeSystem","Sistem","System","System","Système","Sistema","Sistema","Sistema","Системная","跟随系统","システム","시스템"],
  ["themeLight","Açık","Light","Hell","Clair","Claro","Chiaro","Claro","Светлая","浅色","ライト","라이트"],
  ["themeDark","Koyu","Dark","Dunkel","Sombre","Oscuro","Scuro","Escuro","Тёмная","深色","ダーク","다크"],
  ["languageLabel","Arayüz dili","Interface language","Oberflächensprache","Langue de l'interface","Idioma de la interfaz","Lingua dell'interfaccia","Idioma da interface","Язык интерфейса","界面语言","表示言語","인터페이스 언어"],
  ["recordingIndicator","Kayıt yapılıyor","Recording","Aufnahme läuft","Enregistrement","Grabando","Registrazione","Gravando","Идёт запись","正在录音","録音中","녹음 중"],
  ["sizeMB","{n} MB","{n} MB","{n} MB","{n} Mo","{n} MB","{n} MB","{n} MB","{n} МБ","{n} MB","{n} MB","{n} MB"],
  ["errModelMissing", "Offline model henüz indirilmedi. Ayarlar'dan indir.", "The offline model hasn't been downloaded yet. Download it in Settings.", "Das Offline-Modell wurde noch nicht heruntergeladen. Lade es in den Einstellungen herunter.", "Le modèle hors ligne n'est pas encore téléchargé. Téléchargez-le dans les Paramètres.", "El modelo sin conexión aún no se ha descargado. Descárgalo en Ajustes.", "Il modello offline non è ancora stato scaricato. Scaricalo nelle Impostazioni.", "O modelo offline ainda não foi baixado. Baixe-o nas Configurações.", "Офлайн-модель ещё не загружена. Скачайте её в настройках.", "离线模型尚未下载，请在设置中下载。", "オフラインモデルはまだダウンロードされていません。設定からダウンロードしてください。", "오프라인 모델이 아직 다운로드되지 않았습니다. 설정에서 다운로드하세요."],
  ["errTooLarge", "İstek Groq için çok büyük. ({detail})", "The request is too large for Groq. ({detail})", "Die Anfrage ist für Groq zu groß. ({detail})", "La requête est trop volumineuse pour Groq. ({detail})", "La solicitud es demasiado grande para Groq. ({detail})", "La richiesta è troppo grande per Groq. ({detail})", "A solicitação é grande demais para o Groq. ({detail})", "Запрос слишком велик для Groq. ({detail})", "请求对 Groq 来说过大。（{detail}）", "リクエストが Groq には大きすぎます。（{detail}）", "요청이 Groq에 비해 너무 큽니다. ({detail})"],
];

const TABLE: Record<string, Record<string, string>> = {};
for (const lang of I18N_LANGS) TABLE[lang] = {};
for (const [key, ...vals] of I18N_ROWS) {
  I18N_LANGS.forEach((lang, i) => {
    TABLE[lang][key] = vals[i];
  });
}

export function isUiLang(v: string): v is UiLang {
  return (I18N_LANGS as readonly string[]).includes(v);
}

/** İşletim sistemi dilinden uygun arayüz dilini seçer (desteklenmiyorsa İngilizce). */
export function pickUiLang(locale: string | undefined): UiLang {
  const base = (locale ?? "").toLowerCase().split(/[-_]/)[0];
  return isUiLang(base) ? base : "en";
}

export function translate(lang: string, key: string, vars?: Record<string, string | number>): string {
  let str = TABLE[lang]?.[key] ?? TABLE.en[key] ?? TABLE.tr[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) str = str.split(`{${k}}`).join(String(v));
  }
  return str;
}

export function hasKey(key: string): boolean {
  return key in TABLE.tr;
}
